### ISSUE TITLE
Possible race condition in gpg test cleanup function

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#397]
Fwd: [*Bug#1008349: python-securesystemslib: FTBFS: dh_auto_test: error: pybuild --test -i python{version} -p "3.10 3.9" returned exit code 13*
](https://groups.google.com/g/securesystemslib-dev/c/J2PYMN696sc/m/FncOdnEGBAAJ)
The following error occurred on Debian sid:

```
======================================================================
ERROR: tearDownClass (test_gpg.TestGPGDSA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/.pybuild/cpython3_3.9_securesystemslib/build/tests/test_gpg.py", line 667, in tearDownClass
    shutil.rmtree(self.test_dir)
  File "/usr/lib/python3.9/shutil.py", line 732, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.9/shutil.py", line 665, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.9/shutil.py", line 688, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.9/shutil.py", line 686, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.ssh'

```

**Possible explanation**:
I cannot reproduce the issue, but given the internals of the relevant test and the fact that we haven't seen the error before, a race condition seems likely.

I suppose `gpg-agent`, which is started during the tests by calling `gpg`, is closing/removing the previously opened socket 'S.gpg-agent.ssh', while `shutil.rmtree` is removing the temporary test gpg homedir containing the socket file. I.e. after `shutil.rmtree` has identified the file to be removed, but before it had the chance to actually remove it.

**Possible solution**:
An easy solution would be to configure `shutil.rmtree` to [`ignore_errors=True`](https://docs.python.org/3/library/shutil.html#shutil.rmtree), or to at least ignore `FileNotFoundError`s using a custom [`onerror` handler](https://docs.python.org/3/library/shutil.html#shutil.rmtree) (see [default `onerror`](https://github.com/python/cpython/blob/27ee43183437c473725eba00def0ea7647688926/Lib/shutil.py#L697-L702) for inspiration). This has the downside that we might masquerade errors that we don't want to pass on.

An alternative solution would be to configure `gpg-agent` to not open 'S.gpg-agent.ssh', which IIUC we don't use anyway. But then we might fail on other sockets created by the agent that we do use (e.g. 'S.gpg-agent' ?). See [this SO post](https://unix.stackexchange.com/a/605639) for good pointers to the corresponding gpg docs.

**Comment by lukpueh** [comment]
Hah, looks like there's a ticket to fix this in `shutil`: https://bugs.python.org/issue29699

The [proposed workaround there](https://bugs.python.org/msg288822) matches what I described as easy solution above:
> Another option for users is to set ignore_errors=True, but this ends up ignoring *all* errors, which doesn't seem like the right decision.
>
> Finally, of course, a user could specify some sort of onerror function that explictly ignores FileNotFoundError, but this seems pretty complicated for the common pattern.

**Comment by elfotografo007** [comment]
Hi, I would like to work on this issue.

**Comment by adityasaky** [comment]
Thanks, @elfotografo007!
