### ISSUE TITLE
Support GPG and SSH keys

### ISSUE THREAD

**Issue by lukpueh** [secure-systems-lab/securesystemslib#55]
*securesystemslib* provides an API to import and export public and private keys in PEM (RSA, ECDSA, also cf. #54) or in a proprietary format (Ed25519).

It would be convenient to extend the API so that users can load, e.g. their existing GPG or SSH keys. Note that *securesystemslib* does not necessarily have to provide an API to generate those keys. As @aaaaalbert has mentioned, user might even prefer to use their own well-known toolchain.

**Comment by lukpueh** [comment]
Re SSH: 
Our main (#56) crypto backend [`pyca-cryptography`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/serialization/#openssh-public-key)  supports loading public *rsa* and *ecdsa* ssh keys (*ed25519* is not supported), so it should be easy to add wrappers to `securesystemslib`.
As for private keys, we are already able to handle private *rsa* and *ecdsa* ssh keys stored in PEM format. For some reason *ed25519* does not seem to work:


```python
>>> securesystemslib.interface.import_ed25519_privatekey_from_file(".ssh/id_ed25519")

Traceback (most recent call last):
  File "<input>", line 1, in <module>
    k = intf.import_ed25519_privatekey_from_file(".ssh/id_ed25519")
  File "/Users/lukp/code/securesystemslib/securesystemslib/interface.py", line 549, in import_ed25519_privatekey_from_file
    key_object = securesystemslib.keys.decrypt_key(encrypted_key.decode('utf-8'), password)
  File "/Users/lukp/code/securesystemslib/securesystemslib/keys.py", line 1689, in decrypt_key
    securesystemslib.pyca_crypto_keys.decrypt_key(encrypted_key, passphrase)
  File "/Users/lukp/code/securesystemslib/securesystemslib/pyca_crypto_keys.py", line 843, in decrypt_key
    json_data = _decrypt(encrypted_key, password)
  File "/Users/lukp/code/securesystemslib/securesystemslib/pyca_crypto_keys.py", line 986, in _decrypt
    raise securesystemslib.exceptions.CryptoError('Invalid encrypted file.')
CryptoError: Invalid encrypted file.
```

**Comment by lukpueh** [comment]
Re GPG:

We have implemented GPG in [`in-toto.gpg`](https://github.com/in-toto/in-toto/tree/0.2.1/in_toto/gpg). We should consider moving the implementation to `securesystemslib` at some point.
