### ISSUE TITLE
ecdsa keytypes issue, again

### ISSUE THREAD

**Issue by jku** [secure-systems-lab/securesystemslib#709]
signer API claims to support keytype "ecdsa-sha2-nistp256" but creating a signer for one fails (it would work with "ecdsa"). I think I can work around but this looks like a bug.   

```
Traceback (most recent call last):
  File "/home/jkukkonen/src/tuf-on-ci/.venv/bin/tuf-on-ci-sign", line 8, in <module>
    sys.exit(sign())
             ^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/signer/tuf_on_ci_sign/sign.py", line 61, in sign
    repo.sign(rolename)
  File "/home/jkukkonen/src/tuf-on-ci/signer/tuf_on_ci_sign/_signer_repository.py", line 710, in sign
    self._sign(rolename, md, key)
  File "/home/jkukkonen/src/tuf-on-ci/signer/tuf_on_ci_sign/_signer_repository.py", line 246, in _sign
    signer = self.user.get_signer(key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/signer/tuf_on_ci_sign/_user.py", line 65, in get_signer
    self._signers[key.keyid] = Signer.from_priv_key_uri(uri, key, get_secret)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/securesystemslib/signer/_signer.py", line 119, in from_priv_key_uri
    return signer.from_priv_key_uri(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/securesystemslib/signer/_sslib_signer.py", line 100, in from_priv_key_uri
    return cls(keydict)
           ^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/securesystemslib/signer/_sslib_signer.py", line 50, in __init__
    self._crypto_signer = CryptoSigner.from_securesystemslib_key(key_dict)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jkukkonen/src/tuf-on-ci/.venv/lib/python3.11/site-packages/securesystemslib/signer/_crypto_signer.py", line 201, in from_securesystemslib_key
    raise ValueError(f"unsupported keytype: {public_key.keytype}")
ValueError: unsupported keytype: ecdsa-sha2-nistp256

```

**Comment by jku** [comment]
The reason I need a signer for these arguably wrong keytypes is that I have old metadata that has keys with that keytype: so that's what `Signer.from_priv_key_uri()` is getting
